---
general:
    logging:
        level: INFO
    outdir: .

observations:
    datastore: $GAMMAPY_DATA/hess-dl3-dr1/
    filters:
        - filter_type: par_value
          value_param: Crab
          variable: TARGET_NAME

datasets:
    dataset-type: MapDataset
    stack-datasets: true
    offset-max: 2.5 deg
    psf-kernel-radius: 0.3 deg
    geom:
        skydir: [83.633, 22.014]
        width: [5, 5]
        binsz: 0.04
        coordsys: CEL
        proj: TAN
        axes:
            - name: energy
              hi_bnd: 10
              lo_bnd: 1
              nbin: 4
              interp: log
              node_type: edges
              unit: TeV
    energy-axis-true:
        name: energy
        hi_bnd: 10
        lo_bnd: 1
        nbin: 5
        interp: log
        node_type: edges
        unit: TeV
    binsz-irf: 0.2
    margin-irf: 0.5


fit: {}

flux-points:
    fp_binning:
        hi_bnd: 10
        interp: log
        lo_bnd: 1
        nbin: 2
        unit: TeV
