name: Build dev docs
on: push

jobs:
  dispatch-docs:
    if: github.repository_owner == 'gammapy'
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Gammapy Docs
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REMOTE_DISPATCH }}
          repository: gammapy/gammapy-docs
          event-type: dev-docs
