name: Release

on:
  push:
    tags-ignore:
      - 'v*.dev'

jobs:
  release-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update tags
        run: git fetch --tags --force
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python --version
          pip install -U build
          python -m build --sdist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

  release-github:
    if: github.repository_owner == 'gammapy' && !contains(github.ref_name, 'rc')
    needs: release-pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Gammapy is a Python package for gamma-ray astronomy. See [changelog for this release](https://github.com/gammapy/gammapy/blob/main/docs/release-notes/${{ github.ref_name }}.rst).

  dispatch-docs:
    needs: release-pypi
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Gammapy Docs
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REMOTE_DISPATCH }}
          repository: gammapy/gammapy-docs
          event-type: release
          client-payload: '{"release": "${{ github.ref_name }}"}'

  dispatch-webpage:
    needs: release-github
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Gammapy Webpage
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REMOTE_DISPATCH }}
          repository: gammapy/gammapy-webpage
          event-type: release
          client-payload: '{"release": "${{ github.ref_name }}"}'
